import { environment } from '@environments/environment';

// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_FJOKBf20M',
  aws_user_pools_web_client_id: '7iql37q16ckf38022qesmk809r',
  oauth: {
    domain: 'vct.auth.ap-south-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'profile',
      'openid',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: environment.redirectSignIn,
    redirectSignOut: environment.redirectSignOut,
    responseType: 'code',
    options: {
      AdvancedSecurityDataCollectionFlag: false,
    },
  },
};

export default awsmobile;
