service: 
  name: AuditToolBackend

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  timeout: 20
  environment:
    NODE_ENV: vct
    DB_NAME: auditDb
    DB_USER: wpAuditAdmin
    DB_PASSWORD: dgvshAAYGVavsW
    DB_HOST: vct-audit-db.c29fxzr8c8sn.ap-southeast-1.rds.amazonaws.com
    DB_PORT: 3306
       
functions:
  product:
    handler: src/startup.enrtyPoint
    events:
      - http:
          method: get
          # get products by user id
          path: product/user/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}/phases
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          # return the product by product_phase_id
          path: product/productPhases/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: productPhase/{id}/knowledgeAreas
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: knowledgeArea/{id}/{pid}/questions
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get   
          path: knowledgeArea/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get   
          path: questionCount/knowledgeArea/{pid}/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get   
          path: questionCount/phase/{pid}/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get   
          path: questionCount/product/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get   
          path: productEvidence/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}/questions/{qid}/evidence
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: question/{id}/evidence
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: question/{id}/revertEvidence
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: authTrigger/user
      - http:
          method: put
          path: question/{id}/evidence/{eid}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}/productPhase
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}/question/{qid}/page/{pid}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: user/email/{id}
      - http:
          method: get
          path: user/product/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: evidence/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: product/{id}/question/{qid}/evidence/date/{did}
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: admin/userProducts
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: admin/product
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: admin/products
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: admin/users
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: admin/{pid}/noneproductusers
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: get
          path: admin/organizations
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
      - http:
          method: post
          path: admin/organizations
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-south-1:474717861439:userpool/ap-south-1_FJOKBf20M
  auth-token-trigger:
    handler: src/functions/auth-token-trigger.authToken

